sudo: false
language: rust

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      script:
        - |
            cargo build &&
            travis_wait 30 cargo test &&
            cargo doc
  include:
    - rust: beta
      script:
        - |
            cargo build &&
            travis_wait 30 cargo test
  include:
    - rust: nightly
      script:
      - |
          cargo build &&
          travis_wait 30 cargo test &&
          cargo bench
# TODO: Because caching when installing cargo-travis there can already exists one which fails because cargo install is stupid.
# -f could be used to force installation, but that kinda defeats the point of caching,
# so we just ignore error for now and just cross fingers and hope that there exists cargo-travis.
before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH || true

after_success:
  - cargo coveralls --exclude-pattern tests/
