sudo: false
language: rust

cache:
  cargo: true
  apt: true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

# TODO: Because caching when installing cargo-travis there can already exists one which fails because cargo install is stupid.
# -f could be used to force installation, but that kinda defeats the point of caching,
# so we just ignore error for now and just cross fingers and hope that there exists cargo-travis.
before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH || true

script:
  - |
      cargo build -v
      travis_wait 30 cargo test
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench -v --no-run --all-features;
      fi
      cargo doc -v

after_success:
  - cargo coveralls --exclude-pattern tests/
