sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
    - rust: beta
    - script:
        - |
            cargo build &&
            travis_wait 30 cargo test &&
            cargo doc
  include:
    - rust: nightly
    - script:
      - |
          cargo build &&
          travis_wait 30 cargo test &&
          cargo bench

before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

after_success:
  - cargo coveralls
